app/views/members_views.py
from flask import Blueprint, redirect, render_template, request, url_for
from flask_user import current_user, login_required
from app import db, babel
from app.models.user_models import UserProfileForm
from flask import current_app as app
import gettext

members_blueprint = Blueprint('members', __name__, template_folder='templates')


@babel.localeselector
def get_locale():
    translations = [str(translation) for translation in
                    babel.list_translations()]
    return request.accept_languages.best_match(translations)


def set_lang(lang):
    i18n_dir = app.config['BABEL_TRANSLATION_DIRECTORIES']
    gettext.install('lang', i18n_dir)
    trans_file = i18n_dir + lang + '/LC_MESSAGES/flask_user'
    tr = gettext.translation(trans_file, 'locale',  languages=[lang])
    tr.install(True)
    app.jinja_env.install_gettext_translations(tr)


@members_blueprint.before_app_request
def before_request():
    lang = get_locale()
    lang = lang if lang else app.config['BABEL_DEFAULT_LOCALE']
    set_lang(lang)

    if request.path.startswith('/admin'):
        if current_user.is_authenticated:
            if not current_user.has_role("admin"):
                return redirect(url_for('user.logout'))
        else:
            return redirect(url_for('user.login'))


@members_blueprint.route('/members/')
@login_required
def member_page():
    return render_template('pages/user_page.html')


@members_blueprint.route('/members/profile/', methods=['GET', 'POST'])
@login_required
def user_profile_page():
    # Initialize form
    # form = UserProfileForm(request.form, current_user)
    form = UserProfileForm()

    # Process valid POST
    if request.method == 'POST' and form.validate():
        # Copy form fields to user_profile fields
        form.populate_obj(current_user)

        # Save user_profile
        db.session.commit()

        # Redirect to home page
        return redirect(url_for('public.home_page'))

    # Process GET or invalid POST
    return render_template('pages/user_profile_page.html',
                           form=form)

app/views/public_views.py
from flask import Blueprint, render_template

public_blueprint = Blueprint('public', __name__, template_folder='templates')


@public_blueprint.route('/')
def home_page():
    return render_template('pages/home_page.html')

app/templates/pages/home_page.html
{% extends "common/page_base.html" %}

{% block content %}
    <h2>{%trans%}Home Page{%endtrans%}</h2>
    <p><a href={{ url_for('user.register') }}>{%trans%}Register{%endtrans%}</a></p>
    <p><a href={{ url_for('user.login') }}>{%trans%}Sign in{%endtrans%}</a></p>
    <p><a href={{ url_for('public.home_page') }}>{%trans%}Home Page{%endtrans%}</a> (accessible to anyone)</p>
    <p><a href={{ url_for('members.member_page') }}>{%trans%}Member Page{%endtrans%}</a> (login_required: member@example.com / Password1)</p>
    <p><a href={{ url_for('admin.index') }}>{%trans%}Admin Page{%endtrans%}</a> (roles_required: admin@example.com / Password1)</p>
    <p><a href={{ url_for('user.logout') }}>{%trans%}Sign out{%endtrans%}</a></p>
{% endblock %}

app/templates/pages/user_page.html
{% extends "common/page_base.html" %}  {# common/page_base.html extends layout.html #}

{% block content %}
    <h2>{%trans%}Members page{%endtrans%}</h2>
{% endblock %}

app/templates/pages/user_profile_page.html
{% extends "common/page_base.html" %}  {# common/page_base.html extends layout.html #}

{% block content %}
  <h1>{{ _('User profile') }}</h1>

  <p><a href="{{ url_for('user.change_password') }}">{{ _('Change password') }}</a></p>

{% endblock %}